import Header from "@/components/header";
import { Metadata } from "next";
import MinorLayerProvider from "./minor-layer-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="w-full relative">
      <MinorLayerProvider>
        <Header />
        {children}
      </MinorLayerProvider>
    </main>
  );
}
