import { Metadata } from "next";
import MinorLayerProvider from "./minor-layer-provider";
import LeftSidebar from "@/components/sidebar/left-sidebar";
import RightSideBar from "@/components/sidebar/right-sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="w-full relative ">
      <MinorLayerProvider>
        <div className="w-full flex items-start h-screen overflow-y-hidden">
          <LeftSidebar />
          <div className="w-full h-screen overflow-y-auto py-10">
            {children}
          </div>
          <RightSideBar />
        </div>
      </MinorLayerProvider>
    </main>
  );
}
